arguments:
  zero_correction:
    # original arguments
    config_path: configs/xtc_config.json
    config_name: xtc_p16_phy
    detector_index: 8
    trigger_index: 7
    neg_matrix: results/overall/neg_restrained_xtalk_matrix.csv
    pos_matrix: results/overall/pos_restrained_xtalk_matrix.csv
    out_dir: results/zero_correction
    # cuts
    trigger_max: 9999
    trigger_threshold: 50

